// Code generated by scripts/gen-memory-ontology-seed.c from src/rel_types.c
// SEED_ONTOLOGY. DO NOT EDIT BY HAND.
// Regenerate when the C table changes; ontology_conformance_test.go compares
// this against testdata/ontology_seed.tsv, generated in the same walk.

package memory

// seedOntology is the memory module's relation table: the entity kinds the
// write gate allows at each end, and the sensitivity tier the recall gate
// reads. NodeOther in a kind list is the ANY wildcard.
var seedOntology = []relTypeDef{
	{RelType: "works_for", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodeOrg}, Sensitivity: SensNormal},
	{RelType: "member_of", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodeOrg}, Sensitivity: SensNormal},
	{RelType: "has_role", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodeScalar}, Sensitivity: SensNormal},
	{RelType: "spouse", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePerson}, Sensitivity: SensPII},
	{RelType: "knows", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePerson}, Sensitivity: SensPII},
	{RelType: "parent_of", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePerson}, Sensitivity: SensPII},
	{RelType: "child_of", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePerson}, Sensitivity: SensPII},
	{RelType: "lives_in", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePlace}, Sensitivity: SensPII},
	{RelType: "born_in", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodePlace}, Sensitivity: SensPII},
	{RelType: "located_in", HeadKinds: []NodeKind{NodeOther}, TailKinds: []NodeKind{NodePlace}, Sensitivity: SensNormal},
	{RelType: "device_has_ip", HeadKinds: []NodeKind{NodeDevice}, TailKinds: []NodeKind{NodeIp}, Sensitivity: SensNormal},
	{RelType: "has_hostname", HeadKinds: []NodeKind{NodeDevice}, TailKinds: []NodeKind{NodeScalar}, Sensitivity: SensNormal},
	{RelType: "age", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodeScalar}, Sensitivity: SensPII},
	{RelType: "also_known_as", HeadKinds: []NodeKind{NodePerson}, TailKinds: []NodeKind{NodeOther}, Sensitivity: SensNormal},
	{RelType: "supersedes", HeadKinds: []NodeKind{NodeOther}, TailKinds: []NodeKind{NodeOther}, Sensitivity: SensNormal},
	{RelType: "linked_policy", HeadKinds: []NodeKind{NodeOther}, TailKinds: []NodeKind{NodeOther}, Sensitivity: SensNormal},
	{RelType: "decided_by", HeadKinds: []NodeKind{NodeOther}, TailKinds: []NodeKind{NodePerson}, Sensitivity: SensNormal},
}
