package memory

import (
	"math"
	"strconv"
	"strings"
	"testing"
)

// Differential check against the C recall gate itself.
//
// All three fixtures are memory_pii_gate.c's own answers, generated by
// scripts/gen-memory-pii-fixtures.c (its header carries the exact build and run
// lines). This gate decides whether a private fact reaches a prompt, so an
// expectation written by reading the C would be worth very little: the reading
// and the port would share whatever the reader got wrong.
//
//   - pii_turns.tsv: every cue the C scans for, plus near-misses of each,
//     across seven sentence frames.
//   - pii_sensitivity.tsv: every seed row (asked of the seed table, not listed)
//     both canonically and through a label that only matches after
//     normalization, plus unseeded names that must still be gated by shape and
//     names that must not be.
//   - pii_inject.tsv: every tier crossed with twelve confidences and both
//     answers to "did the turn ask", with the confidence carried as a raw bit
//     pattern so the floor and NaN cases are exact.

func TestTurnRequestsSensitiveMatchesTheCGate(t *testing.T) {
	asked, notAsked := 0, 0
	for _, row := range fixtureRows(t, "testdata/pii_turns.tsv") {
		if len(row) != 2 {
			t.Fatalf("malformed fixture row %q", strings.Join(row, "\t"))
		}
		text := unescapeField(row[0])
		want := atoi(t, row[1], row) == 1
		if got := TurnRequestsSensitive(text); got != want {
			t.Fatalf("TurnRequestsSensitive(%q) = %v, C = %v", text, got, want)
		}
		if want {
			asked++
		} else {
			notAsked++
		}
	}
	// A corpus where every turn asked (or none did) would agree with a gate that
	// ignored its input entirely.
	if asked == 0 || notAsked == 0 {
		t.Errorf("corpus is one-sided: asked=%d not_asked=%d", asked, notAsked)
	}
}

func TestRelSensitivityMatchesTheCGate(t *testing.T) {
	seen := map[RelSensitivity]int{}
	for _, row := range fixtureRows(t, "testdata/pii_sensitivity.tsv") {
		if len(row) != 2 {
			t.Fatalf("malformed fixture row %q", strings.Join(row, "\t"))
		}
		label := unescapeField(row[0])
		want := RelSensitivity(atoi(t, row[1], row))
		if got := RelSensitivityOf(label); got != want {
			t.Fatalf("RelSensitivityOf(%q) = %d, C = %d", label, got, want)
		}
		seen[want]++
	}
	// All three tiers have to appear, or a classifier stuck on one of them would
	// agree with most of the corpus.
	for _, tier := range []RelSensitivity{SensNormal, SensPII, SensSecret} {
		if seen[tier] == 0 {
			t.Errorf("tier %d never appears in the corpus; the classifier is undercovered", tier)
		}
	}
	t.Logf("classified %d labels: normal=%d pii=%d secret=%d",
		seen[SensNormal]+seen[SensPII]+seen[SensSecret], seen[SensNormal], seen[SensPII],
		seen[SensSecret])
}

func TestShouldInjectMatchesTheCGate(t *testing.T) {
	injected, withheld := 0, 0
	sawNaN := false
	for _, row := range fixtureRows(t, "testdata/pii_inject.tsv") {
		if len(row) != 4 {
			t.Fatalf("malformed fixture row %q", strings.Join(row, "\t"))
		}
		sens := RelSensitivity(atoi(t, row[0], row))
		bits, err := strconv.ParseUint(row[1], 16, 64)
		if err != nil {
			t.Fatalf("bad confidence bits %q: %v", row[1], err)
		}
		confidence := math.Float64frombits(bits)
		asked := atoi(t, row[2], row) == 1
		want := atoi(t, row[3], row) == 1

		if got := ShouldInject(sens, confidence, asked); got != want {
			t.Fatalf("ShouldInject(%d, %v, %v) = %v, C = %v", sens, confidence, asked, got, want)
		}
		if math.IsNaN(confidence) {
			sawNaN = true
			if want {
				t.Fatalf("the C injected at a NaN confidence for tier %d; that is fail-open", sens)
			}
		}
		if want {
			injected++
		} else {
			withheld++
		}
	}
	if injected == 0 || withheld == 0 {
		t.Errorf("corpus is one-sided: injected=%d withheld=%d", injected, withheld)
	}
	if !sawNaN {
		t.Error("no NaN confidence in the corpus; the fail-closed comparison is untested")
	}
}

// Removing "ip address" from the cue list changes no answer, because "address"
// already matches everything it does. That is the only such cue: dropping any
// other one is caught by the corpus. Pinned here so a future cue that is quietly
// dead on arrival is visible, rather than looking tested because the corpus
// contains it.
func TestOnlyOneTurnCueIsRedundant(t *testing.T) {
	var redundant []string
	for _, cue := range sensitiveTurnCues {
		for _, other := range sensitiveTurnCues {
			if other != cue && ciContains(cue, other) {
				redundant = append(redundant, cue+" (covered by "+other+")")
				break
			}
		}
	}
	if len(redundant) != 1 || !strings.HasPrefix(redundant[0], "ip address") {
		t.Errorf("redundant cues = %v, want exactly [ip address]", redundant)
	}
}

// RelSensitivityOf falls back to the raw label when normalization empties it.
// That branch cannot produce a different answer: normalization only empties a
// label with no alphanumerics at all, and every token in both lists contains
// some, so no token can match the raw label either. Deleting the fallback is
// therefore invisible to the corpus -- assert the reason instead, so a token
// that ever breaks it (a punctuation-only token) fails here.
func TestEmptyNormalizationCannotMatchAToken(t *testing.T) {
	for _, token := range append(append([]string{}, secretTokens...), piiTokens...) {
		if normalizeRelType(token) == "" {
			t.Errorf("token %q has no alphanumerics; the raw-label fallback is now reachable "+
				"and must be tested, not assumed inert", token)
		}
	}
	// And the labels that do normalize away all classify open, via either path.
	for _, label := range []string{"___", "---", "!!!", " ", "..."} {
		if got := RelSensitivityOf(label); got != SensNormal {
			t.Errorf("RelSensitivityOf(%q) = %d, want %d", label, got, SensNormal)
		}
	}
}

// The decisions the gate exists to make, stated outright rather than left to a
// fixture to imply. If the C ever changed one of these the fixture would change
// with it and the differential tests would still pass -- these would not.
func TestRecallGateWithholdsWhatItMust(t *testing.T) {
	if ShouldInject(SensSecret, 1.0, true) {
		t.Error("a credential was injected; credentials are served through the vault, never context")
	}
	if ShouldInject(SensPII, 1.0, false) {
		t.Error("a regulated identifier was injected into a turn that did not ask for it")
	}
	if !ShouldInject(SensPII, 1.0, true) {
		t.Error("a regulated identifier was withheld from a turn that explicitly asked")
	}
	if ShouldInject(SensNormal, math.NaN(), true) {
		t.Error("a NaN confidence passed the floor; the gate must fail closed")
	}
	if !ShouldInject(SensNormal, ConfidenceFloor, false) {
		t.Error("a fact exactly at the floor was withheld; the floor is inclusive")
	}
	// An unseeded relation whose name denotes a credential must not become
	// injectable just because the ontology has never heard of it.
	if got := RelSensitivityOf("my_router_password"); got != SensSecret {
		t.Errorf("unseeded credential-shaped relation classified %d, want %d", got, SensSecret)
	}
	if got := RelSensitivityOf("favorite_color"); got != SensNormal {
		t.Errorf("ordinary unseeded relation classified %d, want %d", got, SensNormal)
	}
	// A name carrying both a credential token and an identifier token is a
	// credential: the stricter tier wins, so it is never pre-injected.
	if got := RelSensitivityOf("email_password"); got != SensSecret {
		t.Errorf("credential-and-identifier relation classified %d, want %d", got, SensSecret)
	}
}
